export default {
  category: [
    {
      id: '1',
      category: 'donuts',
      iconwhite: require('./Assets/white1.png'),
      iconBrown: require('./Assets/Brown1.png'),
    },
    {
      id: '2',
      category: 'ice-cream',
      iconwhite: require('./Assets/white2.png'),
      iconBrown: require('./Assets/Brown2.png'),
    },
    {
      id: '3',
      category: 'cake',
      iconwhite: require('./Assets/white3.png'),
      iconBrown: require('./Assets/Brown3.png'),
    },
    {
      id: '4',
      category: 'lollipop',
      iconwhite: require('./Assets/white4.png'),
      iconBrown: require('./Assets/Brown4.png'),
    },
    {
      id: '5',
      category: 'cupcakes',
      iconwhite: require('./Assets/white5.png'),
      iconBrown: require('./Assets/Brown5.png'),
    },
  ],
  product: [
    {
      id: '1',
      caregoryid: '1',
      name: 'Chocolate Frosted',
      price: '3',
      kkal: '158',
      weight: '50g',
      images: require('./Assets/a1.png'),
      about:
        'Chocolate Frosted Donut based on the calories, fat, protein, carbs and other nutrition information submitted for Chocolate Frosted Donut.',
    },
    {
      id: '2',
      caregoryid: '1',
      name: 'Cinnamon Twist',
      price: '2.88',
      kkal: '148',
      weight: '45g',
      images: require('./Assets/a2.png'),
      about:
        'twist doughnuts are a cross between crunchy churros and soft, fluffy beignets. Shape the dough into twists',
    },
    {
      id: '3',
      caregoryid: '1',
      name: 'cruller',
      price: '3.5',
      kkal: '160',
      weight: '55g',
      images: require('./Assets/a3.png'),
      about:
        'A cruller is a deep-fried pastry popular in the US and Canada often made from a rectangle of dough, with a cut made in the middle that allows',
    },
    {
      id: '4',
      caregoryid: '1',
      name: 'Strawberry Frosted',
      price: '4',
      kkal: '200',
      weight: '60g',
      images: require('./Assets/a4.png'),
      about:
        "strawberry frosting is really simple. Confectioners sugar, blended fresh strawberries, and a little vanilla extract. It's important to totally",
    },
    {
      id: '5',
      caregoryid: '1',
      name: 'Blueberry',
      price: '4.5',
      kkal: '190',
      weight: '55g',
      images: require('./Assets/a5.png'),
      about:
        "blueberries inside, they're coated in a blueberry jam glaze. It doesn't get much more delicious than this, y'all! These donuts are so easy to make and the whole family",
    },
    {
      id: '6',
      caregoryid: '2',
      name: 'Almond',
      price: '5',
      kkal: '254',
      weight: '60ml',
      images: require('./Assets/b1.png'),
      about:
        'Roasted Almond Ice Cream is a perfect treat for sweet lovers. It has an unforgettable nutty flavour, which is drool worthy! The slow roasted almonds makes this dish more soft and creamy as well as crunchy',
    },
    {
      id: '7',
      caregoryid: '2',
      name: 'Blueberry',
      price: '3.5',
      kkal: '256',
      weight: '55ml',
      images: require('./Assets/b2.png'),
      about:
        'blueberries, a handful of frozen berries makes a delicious treat as well. Because eating frozen blueberries too quickly can cause discomfor',
    },
    {
      id: '8',
      caregoryid: '2',
      name: 'Dark Chocolate',
      price: '2.99',
      kkal: '215',
      weight: '60ml',
      images: require('./Assets/b3.png'),
      about:
        'This dark chocolate ice cream is dark, creamy, and rich. It’s a great base for a multitude of combinations. I’m thinking it needs a salted caramel drizzle.',
    },
    {
      id: '9',
      caregoryid: '2',
      name: 'Peanut Butter',
      price: '4',
      kkal: '243',
      weight: '50ml',
      images: require('./Assets/b4.png'),
      about:
        'peanut butter ice cream is a special treat especially when topped with dark fudge sauce! Use creamy peanut butter for a smooth ice cream or crunchy for a bit of texture',
    },
    {
      id: '10',
      caregoryid: '2',
      name: 'Mango',
      price: '3.99',
      kkal: '280',
      weight: '70ml',
      images: require('./Assets/b5.png'),
      about:
        'King of Fruits! Mangoes impart a luscious creamy texture and rich flavour to this delicious frozen dessert. This ice-cream is available in the market but can also be made at home easily using fresh sweet mangoes or frozen mango',
    },
    {
      id: '11',
      caregoryid: '3',
      name: 'Vanilla Birthday Cake with Old-Fashioned Vanilla Buttercream',
      price: '150',
      kkal: '4565',
      weight: '1.5 pound',
      images: require('./Assets/c1.png'),
      about:
        "vanilla birthday cake is a cake eaten as part of a birthday celebration. Birthday cakes are often layer cakes with frosting served with small lit candles on top representing the celebrant's age",
    },
    {
      id: '12',
      caregoryid: '3',
      name: 'Triple Chocolate Cake',
      price: '199',
      kkal: '5620',
      weight: '2 pound',
      images: require('./Assets/c2.png'),
      about:
        "chocolate cake you've been dreaming of! A slice of Moist Chocolate Cake layered with chocolate frosting with a bite taken out with.",
    },
    {
      id: '13',
      caregoryid: '3',
      name: 'Carrot Cake',
      price: '145',
      kkal: '4510',
      weight: '1 pound',
      images: require('./Assets/c3.png'),
      about:
        'Carrot cake is cake that contains carrots mixed into the batter. Most modern carrot cake recipes have a white cream cheese frosting',
    },
    {
      id: '14',
      caregoryid: '3',
      name: 'Romantic Wedding Cakes',
      price: '150',
      kkal: '4990',
      weight: '1.5 pound',
      images: require('./Assets/c4.png'),
      about:
        'Romantic Wedding Cakes We Love · Tiered Wedding Cakes from Icing on The Cake Of course if you prefer to stick to traditional white',
    },
    {
      id: '15',
      caregoryid: '3',
      name: 'Spiderweb Cake',
      price: '169',
      kkal: '5830',
      weight: '2 pound',
      images: require('./Assets/c5.png'),
      about:
        'spiderweb cake is perfect for Halloween! A rich black cocoa cake with an orange flavoured buttercream and spiderweb piped all around',
    },
    {
      id: '16',
      caregoryid: '4',
      name: 'Pink Lemonade Lollipop',
      price: '1.5',
      kkal: '85',
      weight: '10g',
      images: require('./Assets/d1.png'),
      about:
        'Pink Lemonade. Introducing our 10-count Pink Lemonade bag! This is just one of our many best-selling flavors. Perfect for party',
    },
    {
      id: '17',
      caregoryid: '4',
      name: 'Coffee Lollipop',
      price: '1,8',
      kkal: '112',
      weight: '10g',
      images: require('./Assets/d2.png'),
      about:
        '“Café Latté Lollypops” are definitely for coffee lovers as they have a distinct coffe flavor upon first lick. Made from heavy cream, butter, and Colombian coffee, they’d make a pretty',
    },
    {
      id: '18',
      caregoryid: '4',
      name: 'Bourbon Lollipops',
      price: '2',
      kkal: '125',
      weight: '12g',
      images: require('./Assets/d3.png'),
      about:
        'Bourbon is so delicious that someone went and made lollipops that taste like it! Keep these suckers away from the kids, though',
    },
    {
      id: '19',
      caregoryid: '4',
      name: 'Pressed Flower Lollipops',
      price: '3',
      kkal: '165',
      weight: '15g',
      images: require('./Assets/d4.png'),
      about:
        'Flower Lollipops make beautiful favours for any wedding, event or social occasion, a true show stopper.',
    },
    {
      id: '20',
      caregoryid: '5',
      name: 'Triple Salted Caramel Cupcakes',
      price: '5',
      kkal: '240',
      weight: '50g',
      images: require('./Assets/e1.png'),
      about:
        'These triple threat salted caramel cupcakes are epic...salted caramel in the cupcake, in the frosting and drizzled on top',
    },
    {
      id: '21',
      caregoryid: '5',
      name: 'Strawberry Cupcakes',
      price: '4.99',
      kkal: '256',
      weight: '45g',
      images: require('./Assets/e2.png'),
      about:
        'Fresh Strawberry Cupcakes made from scratch! Moist and tender vanilla cupcakes filled with fresh strawberries and topped with strawberry buttercream',
    },
    {
      id: '22',
      caregoryid: '5',
      name: 'Bubbly Champagne Cupcakes',
      price: '3.5',
      kkal: '239',
      weight: '65g',
      images: require('./Assets/e3.png'),
      about:
        'Bubbly Champagne is included in the batter and the luscious frosting of these moist and delicious treats. Champagne not only adds flavor, but the bubbly also lightens up the texture of the cupcake',
    },
    {
      id: '23',
      caregoryid: '5',
      name: 'Harry Potter Butterbeer Cupcakes',
      price: '6',
      kkal: '252',
      weight: '40g',
      images: require('./Assets/e4.png'),
      about:
        'Butterbeer Cupcakes complete with Butterbeer Frosting will make you feel like you are sitting at the Three Broomsticks in Hogsmeade with Harry Potter',
    },
    {
      id: '24',
      caregoryid: '5',
      name: 'Lemon Cupcakes',
      price: '4.99',
      kkal: '258',
      weight: '50g',
      images: require('./Assets/e5.png'),
      about:
        'Lemon cupcakes are bursting with the tangy essence of juicy California lemons and topped with a lemon-vanilla frosting flecked with zest',
    },
  ],
};
